// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoupDiscover.ORM;

#nullable disable

namespace SoupDiscover.Database.SqliteData
{
    [DbContext(typeof(SqliteDataContext))]
    [Migration("20230216155416_sqlite_migration_564")]
    partial class sqlitemigration564
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("SoupDiscover.Core.Repository.Repository", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Repositories");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Repository");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SoupDiscover.ORM.Credential", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CredentialType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("SoupDiscover.ORM.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .HasColumnType("TEXT");

                    b.Property<int>("LicenseType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryCommit")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryType")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("SoupDiscover.ORM.PackageConsumer", b =>
                {
                    b.Property<int>("PackageConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("PackageConsumerId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProjectId");

                    b.ToTable("PackageConsumer");
                });

            modelBuilder.Entity("SoupDiscover.ORM.PackageConsumerPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackageConsumerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackageConsumerId");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageConsumerPackages");
                });

            modelBuilder.Entity("SoupDiscover.ORM.ProjectEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandLinesBeforeParse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAnalysisDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAnalysisError")
                        .HasColumnType("TEXT");

                    b.Property<string>("NugetServerUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SoupDiscover.ORM.GitRepository", b =>
                {
                    b.HasBaseType("SoupDiscover.Core.Repository.Repository");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("CredentialId");

                    b.HasDiscriminator().HasValue("git");
                });

            modelBuilder.Entity("SoupDiscover.ORM.PackageConsumer", b =>
                {
                    b.HasOne("SoupDiscover.ORM.Package", null)
                        .WithMany("PackageConsumers")
                        .HasForeignKey("PackageId");

                    b.HasOne("SoupDiscover.ORM.ProjectEntity", "Project")
                        .WithMany("PackageConsumers")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SoupDiscover.ORM.PackageConsumerPackage", b =>
                {
                    b.HasOne("SoupDiscover.ORM.PackageConsumer", "PackageConsumer")
                        .WithMany("Packages")
                        .HasForeignKey("PackageConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoupDiscover.ORM.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("PackageConsumer");
                });

            modelBuilder.Entity("SoupDiscover.ORM.ProjectEntity", b =>
                {
                    b.HasOne("SoupDiscover.Core.Repository.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("SoupDiscover.ORM.GitRepository", b =>
                {
                    b.HasOne("SoupDiscover.ORM.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId");

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("SoupDiscover.ORM.Package", b =>
                {
                    b.Navigation("PackageConsumers");
                });

            modelBuilder.Entity("SoupDiscover.ORM.PackageConsumer", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("SoupDiscover.ORM.ProjectEntity", b =>
                {
                    b.Navigation("PackageConsumers");
                });
#pragma warning restore 612, 618
        }
    }
}
